package com.mediway.hos.srm.business.center.model.vo.award;

import com.mediway.hos.srm.business.center.model.vo.baseData.CombVo;
import lombok.Data;

@Data
public class AchievementVo {
    private Long rowId;
    private CombVo year;
    private String yearName;
    private String name;
    private CombVo rewardType;
    private String rewardTypeName;
    private String rewardName;
    private CombVo rewardLevel;
    private String rewardLevelName;
    private CombVo rewardGrade;
    private String rewardGradeName;
    private CombVo rewardUnit;
    private String rewardUnitName;
    private String rewardDate;
    private CombVo ourUnitRanking;
    private String ourUnitRankingName;
    private CombVo subUserId;
    private String subUserName;
    private String subDate;
    private Integer dataStatus;
    private String sysNo;
    private String bizType;
    private CombVo deptId;
    private String deptName;
    private String source;
    private String certificateNo;
    private CombVo mainCompleter;
    private String mainCompleterName;
    private CombVo achvCat;
    private String achvCatName;
    private String achvOwner;
    private String awardName;
    private String divisionId;
    private CombVo classCode;
    private String classCodeName;
    private CombVo discipline;
    private String disciplineName;
    private CombVo disciplineTwo;
    private String disciplineTwoName;
    private CombVo disciplineThree;
    private String disciplineThreeName;
    private Integer authorSum;
    private CombVo projectSource;
    private String projectSourceName;
    private String checkStatus;
    private String note;
    private String schoolSign;
    private String unitsum;
    private CombVo fauthorType;
    private String fauthorName;
    private CombVo fauthorTitle;
    private CombVo fauthorSex;
    private String inFauthorCode;
    private String inFauthorId;
    private CombVo inFauthorEduLevel;
    private CombVo inFauthorEduDegree;
    private String operateTime;
    private String awardLevel;
    private CombVo creatorId;
    private String creatorName;
    private String createTime;
    private String awardApplyId;
    private String checkList;
}
