package com.mediway.hos.srm.business.center.model.dto.academic;

import com.mediway.hos.srm.business.center.model.dto.baseData.BaseDto;
import lombok.Data;

import java.math.BigDecimal;
@Data
public class AcConferenceHostDto{
    private Long rowId;
    private String no;
    private String conferenceType;
    private String name;
    private String year;
    private String direction;
    private String subject;
    private Integer numberOfPeople;
    private BigDecimal budgetFundsAmt;
    private String conferenceForm;
    private String onlineUrl;
    private String openDate;
    private String openTime;
    private String closeDate;
    private String closeTime;
    private String city;
    private String address;
    private Integer hostType;
    private Integer isCharge;
    private String chargeManner;
    private String chargeBank;
    private String chargeAccount;
    private String chargeRemark;
    private String registerStartDate;
    private String registerEndDate;
    private String registerManner;
    private String registerUrl;
    private BigDecimal registerFeeAmt;
    private String regFeeRemark;
    private String fapiaoSupplied;
    private String contactPerson;
    private String contactAddress;
    private String contactTel;
    private String contactEmail;
    private String contactWechat;
    private String trafficGuide;
    private String accomGuide;
    private String applicant;
    private Integer dataStatus;
    private String subUserId;
    private String subDate;
    private String subTime;
    private String auditUserId;
    private String auditDate;
    private String auditTime;
    private String auditDesc;
    private String remark;
    private String deptCode;
    private String divisionCode;
    private String disciplineClass;
    private String disciplineCode;
    private Integer paperNum;
    private String fundSource;
    private String intro;
    private String operateTime;
    private String hostUnit;
    private String assistUnit;
    private String conferenceHead;
    private BigDecimal boardFeeAmt;
    private BigDecimal trafficFeeAmt;
    private BigDecimal siteFeeAmt;
    private BigDecimal bookFeeAmt;
    private BigDecimal otherFeeAmt;
    private BigDecimal accomFeeAmt;
    private String conferencePhone;
    private Integer outnumOfPeople;
    private String travelFlag;
    // 下面是查询条件
    private int page;
    private int rows;
    private String startDate;
    private String endDate;
    private Long userId;
    private String userCode;
    private String auditState;
}
