package com.mediway.hos.srm.business.center.model.dto.patent;

import lombok.Data;

@Data
public class PatentInfoDto {
    private Long rowId;
    private String sysNo;
    private String bizType;
    private String name;
    private String patentType;
    private String deptId;
    private String year;
    private String patentNo;
    private String certificateNo;
    private String applyDate;
    private String applyNo;
    private String annDate;
    private String patentee;
    private String annNo;
    private String subUserId;
    private String subDate;
    private Integer dataStatus;
    private String registerDate;
    private String annOrganization;
    private Integer score;
    private String ourUnitRanking;
    private String researchField;
    private String keyWords;
    private String patentCountry;
    private String division;
    private String scope;
    private String state;
    private String checkStatus;
    private String note;
    private Integer authorNumbers;
    private Integer isDuty;
    private String signType;
    private String firstAuthorName;
    private String firstAuthorTitle;
    private String firstAuthorSex;
    private String firstAuthorType;
    private String inFirstAuthorId;
    private String inFirstAuthorCode;
    private String inFirstAuthorEduLevel;
    private String inFirstAuthorEduDegree;
    private String operateTime;
    private String fileIds;
    private Integer isPct;
    private String pctCode;
    private String pctName;
    private String pctDate;
    private String pctPriorityDate;
    private String pctEnterCountry;
    private String applyInfo;
    private String cooperationType;
    private Integer isValid;
    private String endReason;
    private String applyId;
    private String serialNo;
    private String creatorCode;
    private String creatorName;
    private String createTime;
    private int page;
    private int rows;
    private String startDate;
    private String endDate;
    private Long userId;
    private String userCode;
    private String auditState;
}
